# # 模型设置
# resume_path: ./checkpoints/thp_20250722-143748/last_model_1.pth
# load_specific_parts: ['encoder']
model: clf_tm_cv_attnpl_t 

# 训练参数
batch_size: 1
accumulation_steps: 2
warmup_ratio: 0.1
learning_rate: 5e-4 # 5e-4
weight_decay: 1e-5
scheduler_factor: null
scheduler_patience: null
scheduler_threshold: null
scheduler_min_lr: 1e-6
scheduler_type: step_warmup
step_lr_step_size_ratio: 0.2
step_lr_gamma: 0.5

# transfomer结构参数
d_model: 64 # 128
d_rnn: 128
d_inner: 128 # 256
n_layers: 1
n_head: 8
d_k: 16
d_v: 16
t_dropout: 0.1
rnn_dropout: 0
attn_type: flash

# MLP 参数
mlp_out: 1
mlp_dropout: 0.3
mlp_hdw: [128]

# 其他参数
dim: 1
epochs: 150
save_dir: null
cuda_id: "0"

# 数据与控制参数
dataset: ChuanDian
seed: 0
Mc: 3 # 4.5
Mf: 4.5
Twindow: 200
Tfore: 20
dt: 10
context_len: 1
split_by_time: true
use_sampler: true # true
time_order:  [train, val, test]