# resume_path: /home/yzzhang/pjt/chuandian_eq/checkpoints/thp_20250722-130644/last_model_1.pth
# load_specific_parts: ['encoder']
# 模型设置
model: thp
dataset: White
minibatch_training: true
pad_token_id: 1
task_type: tpp
# 训练参数

batch_size: 32
accumulation_steps: 1
warmup_ratio: 0.1
learning_rate: 1e-3 # 5e-4
weight_decay: 1e-5
scheduler_factor: null
scheduler_patience: null
scheduler_threshold: null
scheduler_min_lr: 1e-6
scheduler_type: step_warmup
step_lr_step_size_ratio: 0.2
step_lr_gamma: 0.8

# transfomer结构参数
d_model: 64
d_rnn: 64
d_inner: 64
n_layers: 2
n_head: 8
d_k: 16
d_v: 16
t_dropout: 0.1
rnn_dropout: 0.2
attn_type: flash



# 
num_components: 32

# 其他参数
dim: 1
epochs: 1000
save_dir: null
cuda_id: "0"

# 数据与控制参数
split_by_time: true
time_order:  [train, val, test]
