# resume_path: /root/autodl-tmp/chuandian_eq/checkpoints/lstm_20250624-104548/last_model_1.pth
model: lstm
task_type: regression



batch_size: 128
accumulation_steps:  1
warmup_ratio: None
learning_rate: 1e-3
weight_decay: 1e-5
scheduler_factor: 0.6
scheduler_patience: 5
scheduler_threshold: 0.0001
scheduler_min_lr: 0.000001
scheduler_type: none


lstm_hidden_size: 512
lstm_num_layers: 6
lstm_dropout: 0.3

epochs: 200
save_dir: null
cuda_id: "0"



dataset: QTMSaltonSea
seed: 0
Mag_elaps : [3.5, 4, 4.5, 5]
Mc: 0.6 # 4.5
Mf: 0.6
Twindow: 150
Tfore: 75
dt: 5
context_len: 0
dMag: 0.1
split_by_time: true
time_step: 5
feature_cols: ['Num', 'Mag_max', 'Mag_mean', 'b_lsq', 'a_lsq',
       'b_std_lsq', 'std_gr_lsq', 'b_mlk', 'a_mlk', 'b_std_mlk', 'std_gr_mlk',
       'dM_lsq', 'dM_mlk', 'Energy_sqrt', 'prob_x7_lsq', 'prob_x7_mlk',
       'beta','zvalue' ]