# resume_path: /root/autodl-tmp/chuandian_eq/checkpoints/lstm_20250624-104548/last_model_1.pth
model: lstm
task_type: regression



batch_size: 128
accumulation_steps:  1
warmup_ratio: None
learning_rate: 1e-3
weight_decay: 1e-5
scheduler_factor: 0.6
scheduler_patience: 5
scheduler_threshold: 0.0001
scheduler_min_lr: 0.000001
scheduler_type: none
checkpoints/lstm_20250906-115944

lstm_hidden_size: 256
lstm_num_layers: 4
lstm_dropout: 0.3

epochs: 200
save_dir: null
cuda_id: "0"



dataset: ChuanDian
criterion_name: smooth_l1
criterion_cfg:
   beta: 0.5
seed: 0
Mc: 3 # 4.5
Mf: 3
Mag_elaps: [6, 6.5, 7, 7.5]
Twindow: 360
Tfore: 180   # 100
dt: 10
context_len: 0
dMag: 0.1
split_by_time: true
time_step: 5
feature_cols: ['Num', 'Mag_max', 'Mag_mean', 'b_lsq', 'a_lsq',
       'b_std_lsq', 'std_gr_lsq', 'b_mlk', 'a_mlk', 'b_std_mlk', 'std_gr_mlk',
       'dM_lsq', 'dM_mlk', 'Energy_sqrt', 'prob_x7_lsq', 'prob_x7_mlk',
       'beta','zvalue' ]