# 模型设置
model: classifier_stm_s
dataset: ChinaArray
# 训练参数

batch_size: 64
accumulation_steps: 2
warmup_ratio: 0.1
learning_rate: 5e-4 # 5e-4
weight_decay: 1e-5
scheduler_factor: null
scheduler_patience: null
scheduler_threshold: null
scheduler_min_lr: 1e-6
scheduler_type: step_warmup
step_lr_step_size_ratio: 0.2
step_lr_gamma: 0.5


d_model: 128
d_rnn: 128
d_inner: 256
n_layers: 4
emb_n_layers: 2 
n_head: 8
d_k: 16
d_v: 16
t_dropout: 0.1
rnn_dropout: 0
attn_type: flash

# MLP 参数
mlp_out: 1
mlp_dropout: 0.3
mlp_hdw: [256, 128, 64]

# 其他参数
dim: 3
epochs: 150
save_dir: null
cuda_id: "0"

# 数据与控制参数
seed: 0
Mc: 3 # 4.5
Mf: 6
Twindow: 200
Tfore: 20
dt: 10
context_len: 1
split_by_time: true
use_sampler: true # true
time_order:  [train, val, test]