dataset: ChuanDian
seed: 0
Mc: 3 # 4.5
Mf: 4.5
Twindow: 200
Tfore: 20
dt: 10
context_len: 1
split_by_time: true
use_sampler: true # true
time_order:  [train, val, test]

dataset:  ChinaArray
seed: 0
Mc: 3 # 4.5
Mf: 6
Twindow: 200
Tfore: 20
dt: 10
context_len: 1
split_by_time: true
use_sampler: true # true
time_order:  [train, val, test]

dataset: SCEDC
seed: 0
Mc: 2 # 4.5
Mf: 5
Twindow: 300
Tfore: 150
dt: 10
context_len: 1
split_by_time: true
use_sampler: true # true
time_order:  [train, val, test]