dataset: ChuanDian
seed: 0
Mc: 3 # 4.5
Mf: 4.5
Twindow: 200
Tfore: 20
dt: 10
context_len: 1
split_by_time: true
use_sampler: true # true
time_order:  [train, val, test]

dataset:  ChinaArray
seed: 0
Mc: 3 # 4.5
Mf: 6
Twindow: 200
Tfore: 20
dt: 10
context_len: 1
split_by_time: true
use_sampler: true # true
time_order:  [train, val, test]

b_updater_cfg:
  delta: 0.99
  a0: 20
  init_b_target: 1
b_range: [0.5,2]


dataset: SCEDC
seed: 0
Mc: 2 # 4.5
Mf: 5
Twindow: 300
Tfore: 150
dt: 10
context_len: 1
split_by_time: true
use_sampler: true # true
time_order:  [train, val, test]
Mag_elaps : [5, 5.5, 6, 6.5]
# delta: 0.999

b_updater_cfg:
  delta: 0.98
  a0: 50
  init_b_target: 1
b_range: [0.5,2]


dataset: White
seed: 0
Mc: 0.6 # 
Mf: 4.5
Twindow: 150
Tfore: 75
dt: 5
context_len: 1
split_by_time: true
use_sampler: true # true
time_order:  [train, val, test]
Mag_elaps : [4, 4.5, 5, 5.5]

b_updater_cfg:
  delta: 0.998
  a0: 50
  init_b_target: 1
b_range: [0.5,2]


# 下面的数据集不建议用于分类
dataset: QTMSaltonSea
seed: 0
Mc: 0.6 # 4.5
Mf: 3.8
Twindow: 150
Tfore: 75
dt: 5
context_len: 1
split_by_time: true
use_sampler: true # true
time_order:  [train, val, test]
Mag_elaps : [3.5, 4, 4.5, 5]

dataset: QTMSanJacinto
seed: 0
Mc: 0.6 # 4.5
Mf: 3.5
Twindow: 150
Tfore: 75
dt: 5
context_len: 0
split_by_time: true
use_sampler: true # true
time_order:  [train, val, test]
Mag_elaps : [4, 4.5, 5]



dataset: AZDX
seed: 0
Mc: 4.5 # 4.5
Mf: 5.5
Twindow: 20
Tfore: 2
dt: 10
context_len: 1
split_by_time: true
use_sampler: true # true
time_order:  [train, val, test]