dataset: SCEDC
t_forecast = 13000 # 4000 13000
duration = 30  # 7 30

dataset: St1-2018
seed: 0
minibatch_training: false
split_by_time: true
time_order:  [train, val, test]


catalog_cfg:
  freq: "1D"
  mag_completeness: -0.5
