# Checkpoint warm start
resume_path: ./checkpoints/mixer_tpp_20260203-161948/last_model_1.pth
load_specific_parts: ["encoder"]
# freeze_parts: ["encoder"]
# exclude_freeze_parts: ["input_linear"]

# Model / task
model: mixer_tpp
task_type: tpp
num_event_types: 1
pad_token_id: 1
dim: 1
d_model: 64
dropout: 0.3
num_components: 32

mixer_model_config:
  input_dim: 1
  d_model: 64
  n_layer: 3
  d_intermediate: 128  # Typically 4x d_model; set to 0 to disable MLP
  dropout_prob: 0.1
  attn_layer_idx: [1]

  # Input projection type: linear or mlp
  input_proj_type: mlp
  input_proj_hidden: 128  # MLP hidden dimension; defaults to max(d_model, input_dim) if unset
  input_proj_activation: silu  # Options: gelu | relu | silu
  input_proj_dropout: 0.1

  # Input-layer initialization: default | xavier_uniform | xavier_normal | kaiming_uniform | kaiming_normal | normal | uniform
  input_init: kaiming_uniform
  input_init_scale: 1.5

  ssm_cfg:
    layer: Mamba2Rotary  # Must be set to select the Mamba variant
    # d_conv: 4
    use_conv: false
    rotary_emb_scale_base: 1024

  attn_cfg:
    layer: MHATime
    num_heads: 4
    rotary_emb_dim: 8  # Usually d_model // num_heads // 2
    rotary_emb_scale_base: 1024
    causal: true

  norm_epsilon: 1e-5
  rms_norm: false  # Use RMSNorm instead of LayerNorm

  initializer_cfg:
    initializer_range: 0.01  # Initial weight std; keep default unless needed

  fused_add_norm: false  # Use Triton fused norm (requires support)
  residual_in_fp32: true  # More stable residual precision

# Training
epochs: 500
batch_size: 1
accumulation_steps: 1
learning_rate: 1e-3  # 5e-4
weight_decay: 1e-2
warmup_ratio: 0.1

scheduler_type: step_warmup
scheduler_factor: null
scheduler_patience: null
scheduler_threshold: null
scheduler_min_lr: 1e-6
step_lr_step_size_ratio: 0.2
step_lr_gamma: 0.8

# Runtime
cuda_id: "0"
save_dir: null
seed: 0

# Data
dataset: ChuanDian
minibatch_training: false
split_by_time: true
time_order: [train, val, test]
features_input_keys: ["mag"]
normalize_time_by_token: true
time_scale_base_key: tau_mean

# b-value / loss
predict_b: true
b_range: [0.2, 2]
use_b_updater: true
b_updater_cfg:
  delta: 0.98
  a0: 20
  init_b_target: 1

use_ssm_filter: false
B_range: [1e-4, 1e-2]
use_adaptive_loss_weights: false

loss_weights:
  time_weight: 1
  mag_weight: 1
  b_weight: 0.01
  b_smooth_weight: 1e-7
loss_reduction: per_time
