# resume_path: ./checkpoints/thp_20250622-112950/last_model_1.pth
model: mtpp
num_event_types: 1
pad_token_id: 1
task_type: tpp

batch_size: 32
accumulation_steps: 1
warmup_ratio: 0.1
learning_rate: 1e-3 # 5e-4
weight_decay: 1e-5
scheduler_factor: null
scheduler_patience: null
scheduler_threshold: null
scheduler_min_lr: 1e-6
scheduler_type: none
step_lr_step_size_ratio: 0.2
step_lr_gamma: 0.8

rnn_type: GRU
d_model: 32
rnn_dropout: 0
# 
num_components: 32


dim: 1
epochs: 500
save_dir: null
cuda_id: "0"


dataset: AZDX
seed: 0
minibatch_training: true
split_by_time: true
time_order:  [train, val, test]