# resume_path: /root/autodl-tmp/chuandian_eq/checkpoints/classifier_20250603-142623/last_model_1.pth
# freeze_parts: [transformer, mlp] # [transformer, mlp]
# Model settings
model: reg_attnpl
task_type: regression
dataset: ChuanDian
# Training parameters

batch_size: 64
warmup_ratio: 0.1
learning_rate: 5e-4 # 5e-4
weight_decay: 1e-5
scheduler_factor: null
scheduler_patience: null
scheduler_threshold: null
scheduler_min_lr: 1e-6
scheduler_type: step_warmup
step_lr_step_size_ratio: 0.2
step_lr_gamma: 0.5

# Transformer structure parameters
d_model: 128
d_rnn: 256
d_inner: 256
n_layers: 4
n_head: 8
d_k: 16
d_v: 16
t_dropout: 0.1
rnn_dropout: 0.01
attn_type: flash

# MLP parameters
mlp_out: 1
mlp_dropout: 0.3
mlp_hdw: [256, 128, 64]

# Other parameters
dim: 3
epochs: 150
save_dir: null
cuda_id: "0"

# Data and control parameters
Mc: 3
Mf: 3
Twindow: 200
Tfore: 100
dt: 10
context_len: 0
split_by_time: true
use_sampler: false # true
time_order:  [train, val, test]