model: rf
dataset: ChuanDian
seed: 0
Mc: 3 # 4.5
Mf: 5.5
Twindow: 180
Tfore: 90
dt: 10
context_len: 1
split_by_time: true
t_elaps_mode: window


time_order:  [train, val, test]
Mag_elaps : [5.5,6,6.5,7]